### ISSUE TITLE
Support for building asterisk-amr in OpenWrt

### ISSUE THREAD

**Issue by hailfinger** [traud/asterisk-amr#13]
Hello @traud,

OpenWrt already seems to ship opencore-amr (package fdk-aac, https://github.com/openwrt/packages/tree/master/sound/fdk-aac). Could you please look into providing patches for the OpenWrt asterisk-13.x package (https://github.com/openwrt/telephony/issues/252) as well?

Thank you!

Regards,
Carl-Daniel

**Comment by traud** [comment]
Thank you for reporting and raise the awareness about that other thread. Really interesting finding!

However, somebody has to maintain/create/establish such patches/package. Although I would love to see my patches in more projects, the project owner or some contributor to that project has to add my patches. I am not using OpenWrt. If you are ‘just’ an end-user and not a developer/contributor, you have to find/pay somebody who does this for you. Therefore, I am closing this.
