### ISSUE TITLE
asterisk 16.4.0 and Jitsi - AMR error

### ISSUE THREAD

**Issue by ycaner06** [traud/asterisk-amr#17]
Hello,

First of all , thank you for all effort.

Secondly , I installed your patch on Asterisk 16.4.0 and try to playback a record and couldnt hear any sound. How can we solve this problem .

In addition, asterisk a file converter feature that helps to convert records to another codec format. it can reachable from asterisk console as "file convert source destionation" . is there a way to run this feature for AMR /AMR-WB codecs.

Thanks for support

Information;
Asterisk IP addr : 192.168.1.210
Client Ip addr: 192.168.1.17

Jitsi codec order;
![image](https://user-images.githubusercontent.com/12412027/59182431-6b0c1f80-8b72-11e9-9026-be791155f336.png)

Wireshark filter;
![image](https://user-images.githubusercontent.com/12412027/59182465-81b27680-8b72-11e9-8609-6ca256b3063d.png)

Asterisk console debug;  Playing a record as sln16
![image](https://user-images.githubusercontent.com/12412027/59182523-aa3a7080-8b72-11e9-84c7-c6bca0c4817f.png)

SIP packet , codec order
![image](https://user-images.githubusercontent.com/12412027/59182644-eb328500-8b72-11e9-96a0-4c5c84458981.png)

In addition Asterisk endpoint configuration;
` 
[ycaner]
type=endpoint
transport=transport-udp-v4
context=incoming
auth=ycaner
aors=ycaner
dtmf_mode=rfc4733
rewrite_contact=yes
direct_media=no
disallow=all
allow=amrwb
allow=amr
allow=g722
allow=alaw
allow=ulaw
contact_user=ycaner
force_rport=yes
ice_support=yes
inband_progress=yes
moh_passthrough=yes
`

**Comment by ycaner06** [comment]
Hello, 
I tested on MicroSIP that is working with AMR-WB. it can play any record with sln16.
Thanks

**Comment by ycaner06** [comment]
I found a difference between Jitsi's and MicroSIP that is Reserved flag
Jitsi's RTP packet
![image](https://user-images.githubusercontent.com/12412027/59188276-f2ac5b00-8b7f-11e9-8d03-d3abfce6901e.png)

MicroSIP2s RTP Packet
![image](https://user-images.githubusercontent.com/12412027/59188296-ffc94a00-8b7f-11e9-8876-7c2973b9197a.png)

![image](https://user-images.githubusercontent.com/12412027/59189049-cf82ab00-8b81-11e9-92a2-92112526345c.png)

**Comment by ycaner06** [comment]
Lastly , i shared Pcap files.

[Jitsi-AMR-WB.zip](https://github.com/traud/asterisk-amr/files/3274953/Jitsi-AMR-WB.zip)
[microsip-amr-test.zip](https://github.com/traud/asterisk-amr/files/3274954/microsip-amr-test.zip)


Opened a topic on Jitsi forum : https://community.jitsi.org/t/jitsi-destkop-couldnt-hear-amr-codec-from-asterisk/18436

**Comment by traud** [comment]
I am closing this issue because it is Jitsi and cannot be worked-around on the Asterisk side. Anyway, I added a fix to your thread in the Jitsi Community. If that does not fix this issue here and there is still in an issue on the Asterisk side, please, do not hesitate and reopen this issue here.
