### ISSUE TITLE
file convert command not working for amr

### ISSUE THREAD

**Issue by magacho** [traud/asterisk-amr#18]
Hi, I trying to run this command in asterisk 16: 

`file convert "/app-dir/sounds/samples/campello-o.wav" "/var/lib/asterisk/sounds/pt-br/samples/campello.amr"`
 with asterisk-amk installed and  I got no conversion saying that do not have this converter:
`[2020-08-21 20:15:09.643] WARNING[645]: file.c:1502 ast_writefile: No such format 'amr'`
Am I doing something wrong? 

magacho-Latitude-7480*CLI> core show codecs audio
Disclaimer: this command is for informational purposes only.
It does not indicate anything about your configuration.
      ID TYPE  NAME         FORMAT           DESCRIPTION
------------------------------------------------------------------------------------------------
       8 audio g726         g726             (G.726 RFC3551)
       6 audio alaw         alaw             (G.711 a-law)
       4 audio g723         g723             (G.723.1)
      22 audio speex        speex            (SpeeX)
      23 audio speex        speex16          (SpeeX 16khz)
      24 audio speex        speex32          (SpeeX 32khz)
      26 audio g722         g722             (G722)
      27 audio siren7       siren7           (ITU G.722.1 (Siren7, licensed from Polycom))
      10 audio adpcm        adpcm            (Dialogic ADPCM)
      46 audio silk         silk8            (SILK Codec (8 KHz))
      47 audio silk         silk12           (SILK Codec (12 KHz))
      48 audio silk         silk16           (SILK Codec (16 KHz))
      49 audio silk         silk24           (SILK Codec (24 KHz))
      30 audio g719         g719             (ITU G.719)
      21 audio g729         g729             (G.729A)
      11 audio slin         slin             (16 bit Signed Linear PCM)
      12 audio slin         slin12           (16 bit Signed Linear PCM (12kHz))
      13 audio slin         slin16           (16 bit Signed Linear PCM (16kHz))
      14 audio slin         slin24           (16 bit Signed Linear PCM (24kHz))
      15 audio slin         slin32           (16 bit Signed Linear PCM (32kHz))
      16 audio slin         slin44           (16 bit Signed Linear PCM (44kHz))
      17 audio slin         slin48           (16 bit Signed Linear PCM (48kHz))
      18 audio slin         slin96           (16 bit Signed Linear PCM (96kHz))
      19 audio slin         slin192          (16 bit Signed Linear PCM (192kHz))
       5 audio ulaw         ulaw             (G.711 u-law)
      20 audio lpc10        lpc10            (LPC10)
      29 audio testlaw      testlaw          (G.711 test-law)
      45 audio none         none             (<Null> codec)
       1 audio amr          amr              (AMR)
       2 audio amrwb        amrwb            (AMR-WB)
       7 audio gsm          gsm              (GSM)
      25 audio ilbc         ilbc             (iLBC)
      31 audio opus         opus             (Opus Codec)
       9 audio g726aal2     g726aal2         (G.726 AAL2)
       3 audio codec2       codec2           (Codec 2)
      28 audio siren14      siren14          (ITU G.722.1 Annex C, (Siren14, licensed from Polycom))

**Comment by magacho** [comment]
Just to be more clear I'm pre converting the audios.

**Comment by traud** [comment]
For reading, writing, and converting **files**, an Asterisk format module is required. For an example see https://github.com/traud/asterisk-opus/tree/asterisk-13.7/formats Consequently, this is a feature request. Because I do not need that personally, somebody else has to do it. When you get aware of such a format module, please, link it here.
